# 核心任务

- name: moodle
  hosts: all  
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
    - role: role_common
    - role: role_cloud
    - role: role_apache
    - role: role_mysql
    - role: role_php-fpm
    - role: role_inotify_watch
    - role: role_lamp
    - role: role_init_password
    - role: role_phpmyadmin
    - role: role_9panel
    - role: moodle
    - role: role_end
    
