#Moodle版本，需定期维护
moodle_version: MOODLE_38_STABLE

#Web服务器：apache | nginx，通过交互式选择获取
moodle_webs: apache

#Moodle安装元数据，适用于在不同的环境下安装

moodle_runtime_meta:
  CentOS:
    apache:
      vhost_dir: /etc/httpd/vhost
      vhost_src: vhost.conf
      service: httpd
      owner: apache
    nginx:
      vhost_dir: /etc/nginx/conf.d
      vhost_src: default.conf
      service: nginx
      owner: apache
  Ubuntu:
    apache:
      vhost_dir: /etc/apache2/sites-enabled
      vhost_src: vhost.conf
      service: apache2
      owner: www-data
    nginx:
      host_dir: /etc/nginx/conf.d
      vhost_src: default.conf
      service: nginx
      owner: www-data

moodle_vhost_dir: moodle_runtime_meta.{{ansible_distribution}}.{{moodle_webs}}.vhost_dir
moodle_vhost_src: moodle_runtime_meta.{{ansible_distribution}}.{{moodle_webs}}.vhost_src
moodle_service: moodle_runtime_meta.{{ansible_distribution}}.{{moodle_webs}}.service
moodle_owner: moodle_runtime_meta.{{ansible_distribution}}.{{moodle_webs}}.owner