#Web服务器：apache | nginx，通过交互式选择获取
moodle_webs: apache

moodle_vhost_dir: /etc/httpd/vhost
moodle_vhost_src: vhost.conf
moodle_service: httpd
moodle_owner: apache
moodle_name: "moodle"
moodle_title: "Moodle"
moodle_download_url: "https://github.com/moodle/moodle.git"
moodle_version: "v3.8.1"  #版本号需定期维护
