---
# 9panel
- name: delete www.example.com
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Enabled 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Moodle"];'

# mysql
- name: change my.ini
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: 0644

- name: restart mysql
  service:
    name: mysqld
    state: restarted

# Moodle-LMS
- name: Get WebServer
  shell: 

- name: Create Directory
  file:
    path: /data/wwwroot/moodle
    state: directory
    owner: apache
    group: apache
    mode: 0755
  
- name: Download Moodle-LMS
  git:
    repo: https://github.com/moodle/moodle.git
    dest: /data/wwwroot/moodle
    version: MOODLE_37_STABLE

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

# Change Permission
- name: change permission of /data/wwwroot
  file:
    path: "{{item}}"
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - /data/wwwroot
    - /data/apps

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750

# 初始化 on azure
- name: initialize azure vm
  shell:  waagent -deprovision+user --force
  when: cloud == "azure"
