---
# 9panel
- name: Enabled 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Moodle"];'

# Moodle-LMS
- name: delete www.example.com
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: change my.ini
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: 0644

- name: restart mysql
  service:
    name: mysqld
    state: restarted

- name: Create Directory
  file:
    path: /data/wwwroot/moodle
    state: directory
    owner: apache
    group: apache
    mode: 0755
  
- name: Download Moodle-LMS
  git:
    repo: https://github.com/moodle/moodle.git
    dest: /data/wwwroot/moodle
    version: "{{moodle_version}}"

# 系统通用
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group for Apache
    shell: chown -R {{nextcloud_owner}}:{{nextcloud_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{nextcloud_vhost_src}} dest={{nextcloud_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{nextcloud_service}} state=restarted enabled=yes
